#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: joeward
 * Date: 29/08/2018
 * Time: 08:52
 */



use TestrailAPIRunCreate\GenerateTestRun;



if (is_file($autoload = getcwd() . '/vendor/autoload.php')) {
    require $autoload;
}

$projectname = getopt(null, ["project:"]);

if($projectname == null || $projectname['project'] == null){
    die('Project name is either blank or not added as a param. Append --project=');
}


    $generate = new GenerateTestRun($projectname['project']);
    $generate->createNewRun();


